modification for tmake files

diff --git a/bin/tmake b/bin/tmake
--- a/bin/tmake
+++ b/bin/tmake
@@ -89,51 +89,60 @@ getLangsAndSrcs()
     done
 }
 
-# 命令行参数解析
-args=$(getopt -a -o o: -l makefile,project,qt,opencv -n 'tmake' -- "$@")
-if [ $? != 0 ]; then
-    echo "tmake: parse command line error."
-    exit 1
-fi
-eval set -- "$args"
-while [ "$1" != "--" ]
-do
-    case $1 in
-        --makefile)
-            flagType="makefile"
-            ;;
-        --project)
-            flagType="project"
-            ;;
-        --qt)
-            qt="true"
-            ;;
-        --opencv)
-            ;;
-        -o)
-            if [ -n "$2" ]; then
-                projectFile=$2
-                shift
-            fi
-            ;;
-         *)
-             ;;
-    esac
-    shift
-done
+
+parseCommandArgs()
+{
+    args=$(getopt -a -o o: -l qt,opencv -n 'tmake' -- "$@")
+    if [ $? != 0 ]; then
+        echo "tmake: parse command line error."
+        exit 1
+    fi
+    eval set -- "$args"
+    while [ "$1" != "--" ]
+    do
+        case $1 in
+            --qt)
+                qt="true"
+                ;;
+            --opencv)
+                ;;
+            -o)
+                if [ -n "$2" ]; then
+                    projectFile=$2
+                    shift
+                fi
+                ;;
+             *)
+                 ;;
+        esac
+        shift
+    done
+}
 
 # 根据编译类型进行
-if [ -z $flagType ] || [ "$flagType" = "makefile" ]; then
-    mkdir ../build
+cmd=$1
+if [ "$cmd" = "make" ]; then
+    if [ ! -d ../build ]; then
+        mkdir ../build
+    fi
     cd ../build
     cmake -G "Unix Makefiles" $srcPath
     cmake --build . --config Release
-elif [ "$flagType" = "project" ]; then
+elif [ "$cmd" = "config" ]; then
+    shift
+    parseCommandArgs
     getLangsAndSrcs
     if [ -f $projectFile ]; then
         rm -f $projectFile
     fi
     createCMakeLists
+    echo "Successfully create CMakeLists.txt in current Files."
+elif [ "$cmd" = "run" ]; then
+    exe="../build/$project"
+    echo "Executing $exe:"
+    echo ""
+    $exe
+    echo ""
 fi
 
 exit
